<?php 

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.line.me/v2/bot/richmenu");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n    \"size\":{\n        \"width\":2500,\n        \"height\":1686\n    },\n    \"selected\":false,\n    \"name\":\"Controller\",\n    \"chatBarText\":\"Controller\",\n    \"areas\":[\n        {\n          \"bounds\":{\n              \"x\":551,\n              \"y\":325,\n              \"width\":321,\n              \"height\":321\n          },\n          \"action\":{\n              \"type\":\"message\",\n              \"text\":\"up\"\n          }\n        },\n        {\n          \"bounds\":{\n              \"x\":876,\n              \"y\":651,\n              \"width\":321,\n              \"height\":321\n          },\n          \"action\":{\n              \"type\":\"message\",\n              \"text\":\"right\"\n          }\n        },\n        {\n          \"bounds\":{\n              \"x\":551,\n              \"y\":972,\n              \"width\":321,\n              \"height\":321\n          },\n          \"action\":{\n              \"type\":\"message\",\n              \"text\":\"down\"\n          }\n        },\n        {\n          \"bounds\":{\n              \"x\":225,\n              \"y\":651,\n              \"width\":321,\n              \"height\":321\n          },\n          \"action\":{\n              \"type\":\"message\",\n              \"text\":\"left\"\n          }\n        },\n        {\n          \"bounds\":{\n              \"x\":1433,\n              \"y\":657,\n              \"width\":367,\n              \"height\":367\n          },\n          \"action\":{\n              \"type\":\"message\",\n              \"text\":\"btn b\"\n          }\n        },\n        {\n          \"bounds\":{\n              \"x\":1907,\n              \"y\":657,\n              \"width\":367,\n              \"height\":367\n          },\n          \"action\":{\n              \"type\":\"message\",\n              \"text\":\"btn a\"\n          }\n        }\n    ]\n  }");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Authorization: Bearer elrTlEnZYv9BqQTLFDG+PsaT3VdBjCzs9/nhqkNNGFaHQDveBfVE2xL0ddW+PGl1sK/tCikVIoIq8ZcPaPIkgNIWdRO/QeEEENO0+UzmaKZrcZbCc9DDQ8cyoNuVN3Z0R4ewRaMjlDmMD3rePRDxnQdB04t89/1O/w1cDnyilFU=";
$headers[] = "Content-Type: application/json";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

?>